[build]
  command = "ng build"
  publish = "dist/motorsport-events-admin"

[context.production]
  environment = { NODE_VERSION = "18" }

[context.deploy-preview]
  environment = { NODE_VERSION = "18" }

[context.branch-deploy]
  environment = { NODE_VERSION = "18" }

[[plugins]]
  package = "@netlify/plugin-angular-universal" 