[build]
  command = "npm run build"
  publish = "dist/motorsport-events-admin"

[context.production]
  environment = { NODE_VERSION = "18" }

[context.deploy-preview]
  environment = { NODE_VERSION = "18" }

[context.branch-deploy]
  environment = { NODE_VERSION = "18" } 