export const environment = {
  baseUrl: 'http://localhost:3030',
  accessToken:
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWE2YTYyZTA0MTIxODA4MjhiYzg4MDAiLCJlbWFpbCI6IkRpbW81OUBhYnYuYmciLCJvcmdhbml6YXRvck5hbWUiOiJCYWkgSXZhbiIsImZpcnN0TmFtZSI6IiIsImxhc3ROYW1lIjoiIiwicm9sZSI6ImFkbWluIiwicmVnaW9uIjoiIiwicGhvbmUiOiIwODk3MzM1NTg3IiwiaXNEZWxldGVkIjpmYWxzZSwiaXNBcHByb3ZlZCI6dHJ1ZSwiaWF0IjoxNzA1NDIwMzc3LCJleHAiOjE3MDYyODQzNzd9.YSVaIkMJ4EgoYuh0hWMA-tc05aeIdSZnj_ixia8rbUo',
};
