export const environment = {
  baseUrl: 'http://localhost:3030',
  accessToken:
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTg1NWMyOWVjOGRjNWUzZjJjZGQxYTYiLCJlbWFpbCI6IkRpbW80NUBhYnYuYmciLCJvcmdhbml6YXRvck5hbWUiOiJCYWkgSXZhbiIsImZpcnN0TmFtZSI6IiIsImxhc3ROYW1lIjoiIiwicm9sZSI6ImFkbWluIiwicmVnaW9uIjoiIiwicGhvbmUiOiIwODk3MzM1NTg3IiwiaXNEZWxldGVkIjpmYWxzZSwiaXNBcHByb3ZlZCI6dHJ1ZSwiaWF0IjoxNzA0NTQwODEzLCJleHAiOjE3MDU0MDQ4MTN9.GzAQ1LSyjcZkQQtbSD7aQS27UEhnITZaDQ5i2ynjqgo',
};
