export const environment = {
  baseUrl: 'http://localhost:3030',
  accessToken:
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTg1NWQzMmVjOGRjNWUzZjJjZGQxYWEiLCJlbWFpbCI6IkRpbW9AYWJ2LmJnIiwib3JnYW5pemF0b3JOYW1lIjoiQmFpIEl2YW4iLCJmaXJzdE5hbWUiOiJQZXNobyIsImxhc3ROYW1lIjoiUGVzaG92Iiwicm9sZSI6ImFkbWluIiwicmVnaW9uIjoiIiwicGhvbmUiOiIwODk3MzM1NTg3IiwiaXNEZWxldGVkIjpmYWxzZSwiaXNBcHByb3ZlZCI6dHJ1ZSwiaWF0IjoxNzA0MzUyODkxLCJleHAiOjE3MDUyMTY4OTF9._mvDJK0behVWjBfH6zhhPK9rvC5FErPZESI4leWs63w',
};
